apiVersion: certmanager.k8s.io/v1beta1
kind: ClusterIssuer
metadata:
    name: letsencrypt-prod
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: 'andre.couture@me.com'
        privateKeySecretRef:
            name: letsencrypt-prod
        http01: {}
